version: "3.1"
services:
  web:
    image: node:20.9.0
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run build && npm run start"

